#ifndef DATA_STRUCTURE_LIGHT_H
#define DATA_STRUCTURE_LIGHT_H

#include <glm/glm.hpp>
#include <OpenGLObjects/FrameBuffer.h>

/**
*	\brief A struct to model light
*/
struct Light
{
	glm::vec3 position; /**<< The position of the light*/
	glm::vec3 ambient; /**<< The ambient strength of the light*/
	glm::vec3 diffuse; /**<< The diffuse strength of the light*/
	glm::vec3 specular; /**<< The specular strength of the light*/

	FrameBuffer shadow_map; /**<< The shadowmap generated by this lightsource*/
	glm::mat4 lightSpace; /**<< The light space matrix of this lightsource*/
};

#endif